import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('suggestions can be configured, saved and used inside an activity step', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/schedules/generator');
  await page.evaluate(() => {
    const studio = (window as any).ScheduleStudio;
    localStorage.setItem(studio.STORAGE_KEY, JSON.stringify({ plans: [studio.sanitizePlan({ id: 'nested', learner: 'Sam', name: 'Nested suggestions', days: [] })], activities: [], images: [] }));
  });
  await page.goto('/schedules/generator?plan=nested&day=monday');
  await page.locator('[data-action="add-activity"]').first().click();
  await page.locator('#activityForm [name="title"]').fill('Afternoon routine');
  await page.locator('#activityForm [name="note"]').fill('Keep this parent draft');
  await page.locator('[data-action="add-activity-step"]').click();
  await page.locator('[data-step-field="title"]').fill('Pick a short activity');
  await page.locator('[data-step-kind="0"]').selectOption('suggestion');
  await page.locator('[data-action="configure-step-suggestion"]').click();
  await expect(page.locator('#stepSuggestionDialog')).toBeVisible();
  await expect(page.locator('#suggestionForm [name="start"]')).toHaveAttribute('type', 'hidden');
  await page.locator('#candidateTitle').fill('Fold towels');
  await page.locator('#candidateCategory').fill('Chores');
  await page.locator('#candidateDuration').fill('5');
  await page.locator('[data-action="suggestion-add-candidate"]').click();
  await page.locator('#candidateTitle').fill('Watch a nature video');
  await page.locator('#candidateCategory').fill('Videos');
  await page.locator('#candidateDuration').fill('10');
  await page.locator('#candidateUrl').fill('https://example.com/nature');
  await page.locator('[data-action="suggestion-add-candidate"]').click();
  await page.locator('#suggestionForm [name="rerollMode"]').selectOption('limited');
  await page.locator('#suggestionForm [name="maxRerolls"]').fill('1');
  await page.locator('#suggestionForm [name="allowCategoryChoice"]').check();
  await page.locator('#suggestionForm [name="allowSkip"]').check();
  await page.locator('#suggestionForm [name="animation"]').selectOption('instant');
  const editor = await new AxeBuilder({ page }).include('#stepSuggestionDialog').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(editor.violations, JSON.stringify(editor.violations, null, 2)).toEqual([]);
  await page.locator('#suggestionForm button[type="submit"]').click();
  await expect(page.locator('#stepSuggestionDialog')).not.toBeVisible();
  await expect(page.locator('#activityForm [name="title"]')).toHaveValue('Afternoon routine');
  await expect(page.locator('#activityForm [name="note"]')).toHaveValue('Keep this parent draft');
  await expect(page.locator('.step-suggestion-summary')).toContainText('2 optional activities');
  // Configure again, then cancel: only the saved step config is retained.
  await page.locator('[data-action="configure-step-suggestion"]').click();
  await page.locator('#suggestionForm [name="maxRerolls"]').fill('9');
  await page.locator('#stepSuggestionDialog [data-close-dialog]').last().click();
  await expect(page.locator('.step-suggestion-summary')).toContainText('1 rerolls');
  await page.locator('#activityForm button[type="submit"]').click();
  await expect(page.locator('.activity-card .activity-steps')).toContainText('Fold towels');
  await page.reload();
  await page.locator('[data-action="edit-activity"]').click();
  await expect(page.locator('[data-step-kind="0"]')).toHaveValue('suggestion');
  // Switching back to a manual choice must remain supported after reload.
  await page.locator('[data-step-kind="0"]').selectOption('choice');
  await page.locator('[data-step-kind="0"]').selectOption('suggestion');
  await page.locator('[data-action="configure-step-suggestion"]').click();
  await expect(page.locator('#suggestionForm [name="maxRerolls"]')).toHaveValue('1');
  await expect(page.locator('.suggestion-candidate')).toHaveCount(2);
  await page.locator('#stepSuggestionDialog [data-close-dialog]').last().click();
  await page.locator('#activityForm button[type="submit"]').click();
  const workspace = await page.evaluate(() => JSON.parse(localStorage.getItem('woodles.schedule-planner.v1')!));
  expect(workspace.plans[0].days[0].activities).toHaveLength(1);
  expect(workspace.activities[0].steps[0].kind).toBe('suggestion');
  expect(workspace.suggestionPools).toHaveLength(1);
  const occurrence = workspace.plans[0].days[0].activities[0].occurrenceId;
  const stepId = workspace.plans[0].days[0].activities[0].steps[0].id;
  const exporting = page.waitForEvent('download');
  await page.locator('[data-action="export-plan"]').click();
  const download = await exporting;
  await page.locator('#importFile').setInputFiles((await download.path())!);
  const imported = await page.evaluate(() => JSON.parse(localStorage.getItem('woodles.schedule-planner.v1')!));
  expect(imported.plans[1].days[0].activities[0].steps[0].poolId).toBe(imported.suggestionPools[1].id);
  await page.goto('/schedules/view?plan=nested&day=monday');
  await expect(page.locator('.timeline > .step')).toHaveCount(2); // Activity and finish.
  const nested = page.locator('.nested-suggestion');
  await nested.locator('[data-suggestion-category]').selectOption('Chores');
  await nested.locator('[data-suggestion-draw]').click();
  await expect(nested.locator('.suggestion-result')).toContainText('Fold towels');
  await page.reload();
  await expect(nested.locator('.suggestion-result')).toContainText('Fold towels');
  await nested.locator('[data-suggestion-category]').selectOption('Videos');
  await nested.locator('[data-suggestion-draw]').click();
  await expect(nested.locator('.suggestion-budget')).toContainText('0 rerolls left');
  await nested.locator('[data-suggestion-accept]').click();
  await expect(nested.locator('.suggestion-result a')).toHaveAttribute('href', 'https://example.com/nature');
  await page.locator('#reset').click();
  await expect(nested.locator('[data-suggestion-draw]')).toBeDisabled();
  const state = await page.evaluate((key) => JSON.parse(localStorage.getItem('woodles.schedule-planner.progress.v1')!)['nested:monday'].suggestions[key], occurrence + ':' + stepId);
  expect(state.spins).toBe(2);
  expect(state.accepted).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: test.info().outputPath('nested-suggestion-mobile.png'), fullPage: true });
  const learner = await new AxeBuilder({ page }).include('.nested-suggestion').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(learner.violations, JSON.stringify(learner.violations, null, 2)).toEqual([]);
  expect(errors).toEqual([]);
});
