import { expect, test, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { openActivitySection, openVisualPicker } from './support/schedule-planner';

const state = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('woodles.schedule-planner.v1') || '{}'));

async function newPlan(page: Page) {
  await page.getByRole('button', { name: 'New learner plan', exact: false }).click();
  await page.getByLabel('Learner label', { exact: true }).fill('Sam');
  await page.getByRole('button', { name: 'Create blank plan' }).click();
}

test('shared activity editor creates library cards without a plan and keeps scheduled snapshots independent', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/schedules/generator');
  await page.locator('[data-action="open-content-library"]').click();
  await page.locator('[data-action="library-create"]').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.activity-details')).not.toHaveAttribute('open');
  await expect(page.locator('.activity-steps-disclosure')).not.toHaveAttribute('open');
  await expect(page.locator('#activityForm [name="start"]')).toHaveCount(0);
  await page.locator('#activityForm [name="title"]').fill('Morning routine');
  await page.screenshot({ path: test.info().outputPath('activity-editor-mobile.png'), fullPage: true });
  const editorAxe = await new AxeBuilder({ page }).include('#activityForm').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(editorAxe.violations, JSON.stringify(editorAxe.violations)).toEqual([]);
  await openActivitySection(page, 'details');
  await page.locator('#activityForm [name="category"]').fill('Daily living');
  await page.locator('#activityForm [name="note"]').fill('Water and fruit');
  await openActivitySection(page, 'steps');
  await page.locator('[data-action="add-activity-step"]').click();
  await page.locator('[data-step-field="title"]').fill('Wash hands');
  await openVisualPicker(page);
  await page.locator('#activityForm [name="icon"]').fill('📖');
  await expect(page.locator('.visual-source')).toHaveText('Emoji');
  await page.locator('[data-action="open-image-editor"]').click();
  const png = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 64; canvas.height = 32;
    const context = canvas.getContext('2d')!; context.fillStyle = '#3978c7'; context.fillRect(0, 0, 64, 32);
    return canvas.toDataURL('image/png').split(',')[1];
  });
  await page.locator('#cropSource').setInputFiles({ name: 'routine.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
  await expect(page.locator('#useActivityImage')).toBeEnabled();
  await page.locator('#useActivityImage').click();
  await expect(page.locator('#activityForm [name="imageAssetId"]')).not.toHaveValue('');
  await expect(page.locator('.visual-source')).toHaveText('Uploaded picture');
  await page.locator('#activityForm button[type="submit"]').click();
  await expect(page.locator('#contentLibraryDialog')).toBeVisible();
  const saved = await state(page);
  expect(saved.plans).toHaveLength(0);
  expect(saved.activities[0].steps[0].title).toBe('Wash hands');
  expect(saved.images).toHaveLength(1);
  await page.getByLabel('Search library', { exact: true }).fill('fruit');
  await expect(page.locator('.library-entry')).toHaveCount(1);
  await page.getByLabel('Search library', { exact: true }).fill('missing');
  await expect(page.locator('.library-entry')).toHaveCount(0);
  await page.getByLabel('Search library', { exact: true }).fill('');
  await page.getByLabel('Library category', { exact: true }).selectOption('Daily living');
  await page.getByRole('button', { name: 'Close library', exact: true }).click();
  await newPlan(page);
  await page.locator('[data-action="open-content-library"]').click();
  await page.locator('[data-action="library-add"]').click();
  await page.locator('[data-action="library-add"]').click();
  await page.locator('[data-action="library-edit"]').click();
  await page.locator('#activityForm [name="title"]').fill('Library version');
  await page.locator('#activityForm [name="duration"]').fill('10');
  await page.locator('#activityForm button[type="submit"]').click();
  let current = await state(page);
  expect(current.activities[0].title).toBe('Library version');
  expect(current.plans[0].days[0].activities.map((item: any) => item.title)).toEqual(['Morning routine', 'Morning routine']);
  await page.locator('[data-action="library-add"]').click();
  await page.getByRole('button', { name: 'Close library', exact: true }).click();
  await page.locator('[data-action="edit-activity"]').last().click();
  await expect(page.locator('#activityForm [name="updateLibrary"]')).not.toBeChecked();
  await page.locator('#activityForm [name="title"]').fill('This occurrence');
  await page.locator('#activityForm button[type="submit"]').click();
  expect((await state(page)).activities[0].title).toBe('Library version');
  await page.locator('[data-action="edit-activity"]').last().click();
  await page.locator('#activityForm [name="title"]').fill('Future version');
  await page.locator('#activityForm [name="updateLibrary"]').check();
  await page.locator('#activityForm button[type="submit"]').click();
  current = await state(page);
  expect(current.activities[0].title).toBe('Future version');
  expect(current.plans[0].days[0].activities[0].title).toBe('Morning routine');
  await page.locator('[data-action="open-content-library"]').click();
  await page.locator('[data-action="library-duplicate"]').click();
  page.once('dialog', dialog => dialog.accept());
  await page.locator('[data-action="library-remove"]').first().click();
  expect((await state(page)).activities).toHaveLength(1);
  expect((await state(page)).plans[0].days[0].activities).toHaveLength(3);
  await page.reload();
  await expect(page.locator('.activity-card .activity-visual img')).toHaveCount(3);
  expect(errors).toEqual([]);
});

test('standalone pools support editing, reuse and explicit scheduled-item updates', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/schedules/generator');
  await page.locator('[data-action="open-content-library"]').click();
  await page.getByRole('tab', { name: 'Suggestion pools', exact: true }).click();
  await page.locator('[data-action="library-create"]').click();
  await page.locator('#suggestionForm [name="title"]').fill('Short breaks');
  await page.locator('#candidateTitle').fill('Stretch');
  await page.locator('#candidateCategory').fill('Movement');
  await page.locator('[data-action="suggestion-add-candidate"]').click();
  await page.locator('#suggestionForm [name="rerollMode"]').selectOption('limited');
  await page.locator('#suggestionForm [name="maxRerolls"]').fill('1');
  await page.locator('#suggestionForm button[type="submit"]').click();
  await expect(page.locator('#contentLibraryDialog')).toBeVisible();
  expect((await state(page)).plans).toHaveLength(0);
  expect((await state(page)).suggestionPools).toHaveLength(1);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('Library category', { exact: true }).selectOption('Movement');
  await page.screenshot({ path: test.info().outputPath('pool-library-mobile.png'), fullPage: true });
  const axe = await new AxeBuilder({ page }).include('#contentLibraryDialog').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(axe.violations, JSON.stringify(axe.violations)).toEqual([]);
  await page.getByRole('tab', { name: 'Suggestion pools', exact: true }).focus();
  await page.keyboard.press('ArrowLeft');
  await expect(page.getByRole('tab', { name: 'Activities', exact: true })).toBeFocused();
  await page.keyboard.press('ArrowRight');
  await page.getByRole('button', { name: 'Close library', exact: true }).click();
  await newPlan(page);
  await page.locator('[data-action="open-content-library"]').click();
  await page.locator('[data-action="library-add"]').click();
  await page.locator('[data-action="library-add"]').click();
  await page.locator('[data-action="library-edit"]').click();
  await page.locator('#suggestionForm [name="maxRerolls"]').fill('5');
  await page.locator('#suggestionForm button[type="submit"]').click();
  let current = await state(page);
  expect(current.suggestionPools[0].maxRerolls).toBe(5);
  expect(current.plans[0].days[0].activities.map((item: any) => item.maxRerolls)).toEqual([1, 1]);
  await page.getByRole('button', { name: 'Close library', exact: true }).click();
  await page.locator('[data-action="edit-suggestion"]').first().click();
  await expect(page.locator('#suggestionForm [name="savePool"]')).not.toBeChecked();
  await page.locator('#suggestionForm [name="maxRerolls"]').fill('2');
  await page.locator('#suggestionForm button[type="submit"]').click();
  expect((await state(page)).suggestionPools[0].maxRerolls).toBe(5);
  await page.locator('[data-action="edit-suggestion"]').first().click();
  await page.locator('#suggestionForm [name="maxRerolls"]').fill('3');
  await page.locator('#suggestionForm [name="savePool"]').check();
  await page.locator('#suggestionForm button[type="submit"]').click();
  current = await state(page);
  expect(current.suggestionPools[0].maxRerolls).toBe(3);
  expect(current.plans[0].days[0].activities[1].maxRerolls).toBe(1);
  await page.locator('[data-action="open-content-library"]').click();
  await page.locator('[data-action="library-duplicate"]').click();
  page.once('dialog', dialog => dialog.accept());
  await page.locator('[data-action="library-remove"]').first().click();
  expect((await state(page)).suggestionPools).toHaveLength(1);
  expect((await state(page)).plans[0].days[0].activities).toHaveLength(2);
  expect(errors).toEqual([]);
});

test('nested library drafts cancel cleanly and failed saves keep the complete draft for retry', async ({ page }) => {
  await page.goto('/schedules/generator');
  await page.locator('[data-action="open-content-library"]').click();
  await page.locator('[data-action="library-create"]').click();
  await page.locator('#activityForm [name="title"]').fill('Reusable routine');
  await openActivitySection(page, 'steps');
  await page.locator('[data-action="add-activity-step"]').click();
  await page.locator('[data-step-field="title"]').fill('Choose a break');
  await page.locator('[data-step-kind="0"]').selectOption('suggestion');
  await page.locator('[data-action="configure-step-suggestion"]').click();
  await page.locator('#candidateTitle').fill('Stretch');
  await page.locator('[data-action="suggestion-add-candidate"]').click();
  await page.locator('#suggestionForm button[type="submit"]').click();
  await page.locator('#activityForm').getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.locator('#contentLibraryDialog')).toBeVisible();
  expect(await state(page)).toEqual({});
  await page.locator('[data-action="library-create"]').click();
  await page.locator('#activityForm [name="title"]').fill('Retry card');
  await page.evaluate(() => {
    const save = Storage.prototype.setItem; (window as any).__allowSave = false;
    Storage.prototype.setItem = function(key, value) {
      if (key === 'woodles.schedule-planner.v1' && !(window as any).__allowSave) throw new DOMException('Full', 'QuotaExceededError');
      return save.call(this, key, value);
    };
  });
  await page.locator('#activityForm button[type="submit"]').click();
  await expect(page.locator('#activityError')).toContainText('draft is still here');
  await expect(page.locator('#activityForm [name="title"]')).toHaveValue('Retry card');
  expect(await state(page)).toEqual({});
  await page.evaluate(() => { (window as any).__allowSave = true; });
  await page.locator('#activityForm button[type="submit"]').click();
  await expect(page.locator('#contentLibraryDialog')).toBeVisible();
  expect((await state(page)).activities).toHaveLength(1);
  expect((await state(page)).suggestionPools).toHaveLength(0);
});
