// Initial creature seed — populated once when the bestiary is first opened.
// These are starting cards for designers to edit and customize.

import { uid, now } from './utils';
import type { Creature } from './types';

export function seedCreatures(): Creature[] {
	const created = now();
	return [
		// ── original 20 ──────────────────────────────────────────────────────
		{
			id: uid(),
			name: 'Driftling',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'unspecified',
			kind: '',
			cost: 0,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Has not yet decided what kind of creature it will become.',
			foundIn: '',
			stats: {
				body: 1,
				mind: 1,
				grace: 2,
				heart: 2,
				will: 8,
				spark: 7,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Amoebe',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 0,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'All Will. Almost nothing else. The smallest possible promise.',
			foundIn: '',
			stats: {
				body: 1,
				mind: 0,
				grace: 1,
				heart: 1,
				will: 9,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Hourling',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 0,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Keeps the hour, but cannot tell you what the hour is for.',
			foundIn: '',
			stats: {
				body: 1,
				mind: 5,
				grace: 3,
				heart: 2,
				will: 4,
				spark: 2,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Green Kitten',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Small enough to fit in a teacup. Photosynthesizes in the sun.',
			foundIn: '',
			stats: {
				body: 2,
				mind: 2,
				grace: 4,
				heart: 4,
				will: 5,
				spark: 3,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Pollen Mouse',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Wherever it sneezes, something blooms three weeks later.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 3,
				grace: 5,
				heart: 3,
				will: 4,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Velvet Mole',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Can find anything you\'ve lost, if you describe it carefully.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 4,
				grace: 2,
				heart: 4,
				will: 2,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Sundial Crab',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Casts a shadow that points to noon, whatever time it actually is.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 4,
				grace: 2,
				heart: 4,
				will: 1,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Glimmer Finch',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Sings only at first light, and only what is true.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 4,
				grace: 6,
				heart: 4,
				will: 4,
				spark: 6,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Honeybee Scout',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 2,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Knows the location of every flower for half a mile.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 6,
				grace: 4,
				heart: 6,
				will: 2,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Blossom Doe',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 2,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'She steps through the meadow and the meadow doesn\'t notice.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 2,
				grace: 6,
				heart: 5,
				will: 2,
				spark: 3,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Mossback',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 2,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Patient. Patient. Patient. Then a flower.',
			foundIn: '',
			stats: {
				body: 5,
				mind: 2,
				grace: 3,
				heart: 7,
				will: 1,
				spark: 3,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Lullaby Lamb',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'relational',
			kind: '',
			cost: 2,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Hums the song you were sung to sleep with, even the ones you\'ve forgotten.',
			foundIn: '',
			stats: {
				body: 2,
				mind: 2,
				grace: 7,
				heart: 5,
				will: 3,
				spark: 3,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Lampling',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 2,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Carries a small light. Others stop being afraid in its presence.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 4,
				grace: 7,
				heart: 6,
				will: 4,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Memory Crow',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'relational',
			kind: '',
			cost: 3,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Remembers every face it has ever seen, including the ones in dreams.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 8,
				grace: 6,
				heart: 4,
				will: 3,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Wishing Toad',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'relational',
			kind: '',
			cost: 3,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Sits very still. If you tell it something, it remembers.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 3,
				grace: 7,
				heart: 8,
				will: 2,
				spark: 6,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Compass Stag',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 4,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Walks in whichever direction is most needed.',
			foundIn: '',
			stats: {
				body: 6,
				mind: 6,
				grace: 5,
				heart: 5,
				will: 3,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Tidepool Octopus',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 4,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Solves puzzles you didn\'t know were puzzles.',
			foundIn: '',
			stats: {
				body: 5,
				mind: 8,
				grace: 4,
				heart: 4,
				will: 6,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Phoenixling',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 4,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'A bird the size of a teacup. It will come back.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 3,
				grace: 5,
				heart: 9,
				will: 7,
				spark: 6,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'The First Bee',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 5,
			rarity: 'mythic',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Older than the flowers. Remembers being the only one.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 7,
				grace: 8,
				heart: 9,
				will: 2,
				spark: 8,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Unicorn',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'unspecified',
			kind: '',
			cost: 6,
			rarity: 'mythic',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Approaches only those who weren\'t looking for her.',
			foundIn: '',
			stats: {
				body: 7,
				mind: 6,
				grace: 9,
				heart: 8,
				will: 4,
				spark: 7,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},

		// ── new 20 ───────────────────────────────────────────────────────────
		{
			id: uid(),
			name: 'Dewdrop',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 0,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Small enough to rest on a spider\'s web without breaking it.',
			foundIn: '',
			stats: {
				body: 1,
				mind: 2,
				grace: 7,
				heart: 1,
				will: 1,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Echo Rabbit',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Repeats the last thing anyone said, three heartbeats late.',
			foundIn: '',
			stats: {
				body: 2,
				mind: 3,
				grace: 5,
				heart: 3,
				will: 5,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Fern Sprite',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Hides under fronds. You\'ll find it if you need to.',
			foundIn: '',
			stats: {
				body: 2,
				mind: 2,
				grace: 6,
				heart: 5,
				will: 3,
				spark: 3,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Limestone Snail',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Builds its shell one layer at a time. Very patient about everything.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 1,
				grace: 2,
				heart: 6,
				will: 1,
				spark: 2,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Rust Beetle',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 1,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Turns copper green through sheer persistence.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 3,
				grace: 3,
				heart: 3,
				will: 5,
				spark: 3,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Starling',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'relational',
			kind: '',
			cost: 2,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Mimics the calls of birds it has befriended.',
			foundIn: '',
			stats: {
				body: 2,
				mind: 5,
				grace: 5,
				heart: 6,
				will: 4,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Nettle Wraith',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'relational',
			kind: '',
			cost: 2,
			rarity: 'common',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Born from the anger in a garden. Stings for good reason.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 4,
				grace: 4,
				heart: 2,
				will: 6,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Songflower',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 2,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Blooms only when someone nearby is humming.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 5,
				grace: 6,
				heart: 7,
				will: 3,
				spark: 6,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Argent Fox',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 2,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Solves its problems by thinking three moves ahead.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 7,
				grace: 7,
				heart: 3,
				will: 4,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Moth Knight',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'unspecified',
			kind: '',
			cost: 3,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Wears moonlight as armor. Cannot be seen in direct sun.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 4,
				grace: 7,
				heart: 5,
				will: 5,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Pearl Otter',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'relational',
			kind: '',
			cost: 3,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Teaches other creatures what kindness looks like, by example.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 6,
				grace: 7,
				heart: 7,
				will: 2,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Twine Root',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 3,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Grows downward at exactly the rate the world turns.',
			foundIn: '',
			stats: {
				body: 5,
				mind: 3,
				grace: 3,
				heart: 5,
				will: 4,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Coral Spark',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 3,
			rarity: 'uncommon',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Glows faintly. Other creatures are drawn to its light.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 5,
				grace: 5,
				heart: 6,
				will: 5,
				spark: 7,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Amber Elk',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 3,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Moves through the world slowly, as if wading through old time.',
			foundIn: '',
			stats: {
				body: 6,
				mind: 4,
				grace: 6,
				heart: 5,
				will: 3,
				spark: 4,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Marble Dragon',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'spatial',
			kind: '',
			cost: 4,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'A creature carved by weather and time. Still learning to move.',
			foundIn: '',
			stats: {
				body: 7,
				mind: 6,
				grace: 5,
				heart: 6,
				will: 5,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Silvermane',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'relational',
			kind: '',
			cost: 4,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Speaks in the language of the pack, even when alone.',
			foundIn: '',
			stats: {
				body: 5,
				mind: 7,
				grace: 6,
				heart: 8,
				will: 4,
				spark: 5,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Clockwork Butterfly',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'temporal',
			kind: '',
			cost: 5,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'Counts the days by beating its wings. Never loses the hour.',
			foundIn: '',
			stats: {
				body: 3,
				mind: 8,
				grace: 8,
				heart: 4,
				will: 5,
				spark: 6,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'Verdant Leviathan',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 5,
			rarity: 'rare',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'So large and slow that forests grow in the hollow of its back.',
			foundIn: '',
			stats: {
				body: 8,
				mind: 4,
				grace: 4,
				heart: 7,
				will: 3,
				spark: 6,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'The Ending',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'unspecified',
			kind: '',
			cost: 6,
			rarity: 'mythic',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'The thing every story becomes. Gentle. Inevitable.',
			foundIn: '',
			stats: {
				body: 5,
				mind: 5,
				grace: 5,
				heart: 9,
				will: 6,
				spark: 8,
				substats: {}
			},
			status: {},
			created,
			updated: created
		},
		{
			id: uid(),
			name: 'The Bloom',
			sprite: null,
			pixelated: false,
			composition: null,
			cardStyle: null,
			domain: 'biochemical',
			kind: '',
			cost: 7,
			rarity: 'mythic',
			power: 0,
			toughness: 0,
			abilities: '',
			flavor:
				'After the Ending. Everything grows again.',
			foundIn: '',
			stats: {
				body: 4,
				mind: 6,
				grace: 9,
				heart: 9,
				will: 2,
				spark: 9,
				substats: {}
			},
			status: {},
			created,
			updated: created
		}
	];
}
