// click flavor texts. ~50 glosses rotated semi-randomly.

export const glosses: string[] = [
	'in the margin: a short stroke. you mean it.',
	'a question mark. you do not want to commit yet.',
	'the word "but" written next to the word "and".',
	'an arrow pointing at nothing in particular.',
	'a single greek letter. you cannot read greek.',
	'a date in the future, in pencil, partly erased.',
	'three dots — the gloss continues, somewhere.',
	'an underline that runs out of ink halfway.',
	'a parenthesis opening at the bottom of the page.',
	'a bracket. an unanswered hand.',
	'a checkmark. for what?',
	'a faint cross. you place it next to a noun.',
	'a number, much too small, in superscript.',
	'a word circled. a word un-circled.',
	'a name no scholar has placed.',
	'the abbreviation N.B. — you mean it.',
	'a tiny manicule. an even tinier hand.',
	'the word "see" pointing nowhere.',
	'a query: is this the same passage as before?',
	'an opening quotation mark with no close.',
	'a vertical line in the margin. emphasis at scale.',
	'a wavy line — disagreement, but soft.',
	'a numeral, then nothing.',
	'the latin "vide" — see — pointing at your own earlier hand.',
	'a smudge that resolves, on second look, into a word.',
	'a marginal "no" beside a sentence about saying yes.',
	'a margin filled, briefly, with a list.',
	'a word translated into another word almost like it.',
	'a footnote about a footnote about something elsewhere.',
	'a tiny diagram. a circle inside a circle.',
	'the abbreviation "cf." pointing at a place you remember vaguely.',
	'a bracket around the very bracket you opened earlier.',
	'a word, then the same word, with a different ending.',
	'a date — earlier than the book itself, you would swear.',
	'a phrase you do not remember writing.',
	'a comma where someone, once, did not put one.',
	'an asterisk that opens a footnote you have not yet written.',
	'a paragraph break inserted with a thin pen line.',
	'a marginal hand pointing at another marginal hand.',
	'the word "compare" and a number.',
	'the word "obscure". it is, here, true.',
	'a colon, a hyphen, a colon — you settle on the colon.',
	'the latin "sic" written next to your own sentence.',
	'a single underline so heavy it shows on the next page.',
	'a question that you immediately answer next to it.',
	'a margin so dense the next reader will not find room.',
	'a phrase added in a hand you almost recognize as your own.',
	'the word "elsewhere", and an arrow.',
	'the word "again", and a bracket around it.',
	'a parenthetical that becomes a paragraph that becomes a tradition.',
	'a marginal note that says only: this.',
	'a marginal note that says only: not this.'
];
